name: Build Ghostgram IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set api_id
        run: |
          find . -type f -name "*.json" -exec sed -i '' 's/"api_id": [0-9]*/"api_id": 31594520/g' {} \;

      - name: Install Bazel
        run: |
          brew install bazelisk
          # Создаём симлинк, чтобы скрипт нашёл bazel
          sudo ln -sf $(which bazelisk) /usr/local/bin/bazel

      - name: Generate Xcode project
        run: |
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/bazel-cache" \
            --overrideXcodeVersion \
            generateProject \
            --configurationPath=build-system/template_minimal_development_configuration.json \
            --xcodeManagedCodesigning \
            --disableProvisioningProfiles

      - name: Build IPA
        run: |
          xcodebuild -project Telegram.xcodeproj \
            -scheme Telegram \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ghostgram.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED="NO" \
            CODE_SIGNING_REQUIRED="NO"

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r ghostgram.xcarchive/Products/Applications/Telegram.app Payload/
          zip -r Ghostgram.ipa Payload/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Ghostgram_unsigned
          path: Ghostgram.ipa
